DROP TABLE IF EXISTS PERSONS;
CREATE TABLE PERSONS (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  PERSON_NAME varchar(255) DEFAULT NULL,
  PHONE_NUMBER varchar(255) DEFAULT NULL,
  ADDRESS varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS rents;
CREATE TABLE rents (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  price decimal(10,0) DEFAULT NULL,
  roomId bigint(20) DEFAULT NULL,
  personId bigint(20) DEFAULT NULL,
  startDay date DEFAULT NULL,
  expectedEndDay date DEFAULT NULL,
  realEndDay timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  countOGuestsInRoom int(11) DEFAULT NULL,
  PRIMARY KEY (ID)
); 

DROP TABLE IF EXISTS rooms;
CREATE TABLE rooms (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  capacity int(11) DEFAULT NULL,
  pricePerDay decimal(10,0) DEFAULT NULL,
  room_number int(11) DEFAULT NULL,
  PRIMARY KEY (ID)
);
